---
- name: Apply roles
  hosts: workstation
  roles:
  - role: base-packages
    tags: base-packages
  - role: user
    tags: user
  - role: laptop
    tags: laptop
  - role: jdauphant.dropbox
    become: yes
    tags: dropbox
  - role: dropbox-daemon
    tags: dropbox-daemon
  - role: browsers
    tags: browsers
  - role: wm
    i3_font: DejaVu Sans Mono 12
    terminal_font_size: 14
    tags: wm
  - role: dev
    tags: dev
  - role: gantsign.visual-studio-code
    users:
    - username: "{{ lookup('env', 'USER') }}"
      visual_studio_code_extensions:
      - ms-python.python
      visual_studio_code_settings: {
        "editor.renderWhitespace": true
      }
    tags: visual-studio-code
  - role: mail
    tags: mail
  vars:
    user_uid: 1000
    git_email: rohan@mcgovern.id.au
    mail_user: rohan@mcgovern.id.au
    mail_check_schedule: "*-*-* 0/3:00:00"

    # This machine has broken ACPI so several keys
    # need to be ignored
    laptop_suspend_key: ignore
    laptop_hibernate_key: ignore
    laptop_lid_switch: ignore
