---
- name: Apply roles
  hosts: workstation
  roles:
  - base-packages
  - user
  - role: jdauphant.dropbox
    become: yes
  - dropbox-daemon
  - wm
  - dev
  - role: gantsign.visual-studio-code
    users:
    - username: "{{ lookup('env', 'USER') }}"
      visual_studio_code_extensions:
      - ms-python.python
      visual_studio_code_settings: {
        "editor.renderWhitespace": true
      }
  vars:
    user_uid: 1000
    git_email: rohan@mcgovern.id.au
